/* V4.7 presentation: a fan on the battle canvas, with optional details and safe pointer gestures. */
(() => {
 const $=s=>document.querySelector(s),wide=()=>window.innerWidth>window.innerHeight;
 let usableHeight=window.innerHeight,api=null,centers=[],gesture=null,ghost=null,suppressUntil=0,selected=null,restingTop=Infinity,inputMode='pointer',restoringFocus=false;
 function viewport(){const v=window.visualViewport;if(v&&Math.abs((v.scale||1)-1)>.02)return;const h=Math.min(window.innerHeight||9999,v?.height||9999);if(h>0&&h<9999){usableHeight=Math.floor(h);document.documentElement.style.setProperty('--app-height',usableHeight+'px');}document.body.classList.toggle('fan-short',usableHeight<=330);document.body.classList.toggle('gallery-short',usableHeight<=430);document.body.classList.toggle('gallery-tiny',usableHeight<=330);}
 const makeButton=(text,fn,cls='quiet')=>{const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=text;b.addEventListener('click',fn);return b;};
 const info=document.createElement('dialog');info.id='fanInfo';info.setAttribute('aria-labelledby','fanInfoTitle');info.innerHTML='<div class="dialog-inner"><h2 id="fanInfoTitle">詳しい説明</h2><div class="info-body"></div><div class="actions"></div></div>';const close=makeButton('戻る',()=>info.close(),'primary');info.querySelector('.actions').append(close);document.body.append(info);
 function showInfo(nodes,title='詳しい説明'){cancelDrag('dialog');$('#fanInfoTitle').textContent=title;const body=info.querySelector('.info-body');body.replaceChildren(...nodes.map(n=>n.cloneNode(true)));info.showModal();}
 function compactCards(grid,footer){grid.classList.add('illustrated-choice-grid');const preview=document.createElement('p');preview.className='choice-preview';preview.textContent='カードを選ぶと効果を確認できます。';grid.after(preview);let pending=null,pass=false;const confirm=makeButton('選んでください',()=>{if(!pending||!pending.isConnected)return;pass=true;pending.click();pass=false;},'primary');confirm.disabled=true;footer.append(confirm);
  grid.addEventListener('click',ev=>{if(pass)return;const b=ev.target.closest('button');if(!b||!grid.contains(b))return;ev.stopImmediatePropagation();pending=b;grid.querySelectorAll('button').forEach(x=>x.classList.toggle('choice-selected',x===b));preview.textContent=b.getAttribute('aria-label')||b.textContent;confirm.textContent=b.dataset.remove!==undefined?'この1枚を外す':'この1枚を進化';confirm.disabled=false;},true);
 }
 function setupStory(){const d=$('#storyDialog'),inner=$('#storyBody>.dialog-inner');if(!inner||inner.dataset.fanReady)return;inner.dataset.fanReady='true';const phase=d.dataset.phase||'intro',titles={intro:'護符を選んで、出発',reward:'報酬を1枚選ぶ',route:'次の道を選ぶ',sanctuary:'ここで支度',astrolabe:'HP6で、どちらを得る？',chapter:'次の相手と加護を選ぶ',camp:'最後の支度',evolve:'進化するカードを選ぶ',remove:'外すカードを選ぶ',ready:'次の戦闘へ'};const heading=inner.querySelector('h2'),actions=inner.querySelector('.actions'),content=[...inner.children].filter(x=>x!==heading&&x!==actions&&!x.matches('.eyebrow'));heading.textContent=titles[phase]||heading.textContent;const head=document.createElement('header');head.className='dialog-title';head.append(heading);const main=document.createElement('div');main.className='story-main';inner.replaceChildren(head,main,actions);const groups=content.filter(x=>x.matches('.origin-grid,.reward-grid,.choices,.recap,.result-stat,.journey-map,.ready-scene,.travel-hp'));
  if(phase==='intro'){
    const p=document.createElement('p');p.className='story-blurb';p.textContent='全6戦。どの護符でも、すべてのカードを組み合わせられます。';main.append(p,...groups);const notes=content.filter(x=>x.matches('.journey-note'));if(notes.length){const warning=document.createElement('p');warning.className='story-warning';warning.textContent=notes.some(x=>x.textContent.includes('読み込めません'))?'保存を読み込めません。新しい旅は保存を上書きします。':notes.some(x=>x.textContent.includes('引き継'))?'以前の保存から続けられます。新しい旅は保存を上書きします。':'新しい旅は現在の保存を上書きします。';head.append(warning);}
  }else if(groups.length){const context=content.find(x=>x.tagName==='P');if(context&&!['evolve','remove','ready','complete','defeat'].includes(phase)){context.classList.add('story-blurb');main.append(context);}main.append(...groups);}
  else main.append(...content.filter(x=>x.tagName!=='IMG'));
  if(['reward','evolve','remove'].includes(phase))d.classList.add('card-gallery-dialog');else d.classList.remove('card-gallery-dialog');
  if(phase==='evolve'||phase==='remove'){const grid=main.querySelector('.reward-grid');if(grid)compactCards(grid,actions);}
  if(phase==='ready'){const summary=main.querySelector('.travel-summary');if(summary){head.classList.add('ready-title');head.append(summary);}}
  const routeButtons=main.querySelectorAll('[data-chapter]');for(const b of routeButtons){b.classList.add('illustrated-route');let img=b.querySelector('.route-enemy');if(!img){const choices=[...main.querySelectorAll('[data-chapter]')],source=main.querySelectorAll('.map-stop:nth-child(4) .journey-enemy')[choices.indexOf(b)];if(source){img=source.cloneNode(true);img.classList.add('route-enemy');b.prepend(img);}}if(img){const copy=document.createElement('div');copy.className='route-copy';copy.append(...[...b.childNodes].filter(n=>n!==img));b.append(copy);}}
  const extra=content.filter(x=>!main.contains(x)&&!head.contains(x)&&x.tagName!=='IMG');if(extra.length)actions.prepend(makeButton('説明',()=>showInfo(extra)));
 }
 function setupDialog(id){const d=$('#'+id);if(!d?.open)return;cancelDrag('dialog');if(id==='catalogDialog'||id==='deckDialog'){
   const list=id==='catalogDialog'?$('#catalogList'):$('#deckList');if(!list||list.querySelector('.reference-pick'))return;const items=[...list.querySelectorAll(id==='catalogDialog'?'.catalog-card':':scope>div')],notes=[...list.querySelectorAll(':scope>p')];if(!items.length)return;const preview=document.createElement('p');preview.className='reference-preview';preview.textContent='名前をタップして効果を読む';list.replaceChildren();list.className='reference-grid';for(const item of items){const name=item.querySelector('strong')?.textContent||'',text=item.querySelector('small')?.textContent||'';const b=makeButton(name,()=>{preview.textContent=name+'：'+text;list.querySelectorAll('button').forEach(x=>x.classList.toggle('choice-selected',x===b));},'reference-pick');b.setAttribute('aria-label',name+'。'+text);list.append(b);}list.append(preview);if(notes.length){d.querySelectorAll('[data-fan-note]').forEach(x=>x.remove());const button=makeButton('護符・加護',()=>showInfo(notes,'旅の加護'));button.dataset.fanNote='true';d.querySelector('.actions').prepend(button);}}
 }
 function layoutHand(index=null){selected=index;const forecast=$('#futureIntent');if(forecast){if(usableHeight<=330&&wide()){if(!forecast.querySelector('.forecast-label')){const label=document.createElement('span');label.className='forecast-label';label.textContent='先読み';forecast.append(label);}$('.header-actions').append(forecast);}else $('.game').insertBefore(forecast,$('.table'));}const hand=$('#hand');if(!hand)return;const nodes=[...hand.querySelectorAll(':scope>.hand-item')],box=hand.getBoundingClientRect(),width=box.width||Math.max(320,window.innerWidth-24),count=nodes.length;
  const game=$('.game'),frame=game.getBoundingClientRect(),contentHeight=frame.height||usableHeight,style=getComputedStyle(game),safeTop=parseFloat(style.paddingTop)||0,safeBottom=parseFloat(style.paddingBottom)||0;
  const cardWidth=Math.max(68,Math.min(110,width/(count<=8?6:8))),restHeight=Math.max(72,Math.min(132,usableHeight*.33,contentHeight-safeTop-safeBottom-40-56-26)),gutter=Math.ceil(restHeight*Math.sin(Math.PI/15)+cardWidth*.5*(1-Math.cos(Math.PI/15)))+5,spread=Math.min(Math.max(0,width-cardWidth-2*gutter),Math.max(0,count-1)*cardWidth*.8),step=count>1?spread/(count-1):0;centers=nodes.map((_,i)=>width/2+(i-(count-1)/2)*step);
  const selectedHeight=Math.min(190,Math.max(80,contentHeight-safeTop-safeBottom-40-56-10));const liftWidth=Math.min(width,selectedHeight<140?320:250);hand.style.setProperty('--lift-width',liftWidth+'px');hand.style.setProperty('--lift-height',selectedHeight+'px');hand.style.setProperty('--fan-card-height',restHeight+'px');
  restingTop=Infinity;
  nodes.forEach((n,i)=>{const t=count>1?(i-(count-1)/2)/((count-1)/2):0;const angle=t*12*Math.PI/180,h=restHeight,rise=14+8*(1-t*t);if(box.height>0)restingTop=Math.min(restingTop,box.bottom-rise-h*Math.cos(angle)-cardWidth*.5*Math.abs(Math.sin(angle)));n.hidden=false;n.style.setProperty('--fan-x',(centers[i]-cardWidth/2)+'px');n.style.setProperty('--fan-angle',(t*12)+'deg');n.style.setProperty('--fan-rise',(14+8*(1-t*t))+'px');n.style.setProperty('--fan-width',cardWidth+'px');n.style.setProperty('--fan-z',String(i+1));n.style.setProperty('--lift-x',Math.max(0,Math.min(width-liftWidth,centers[i]-liftWidth/2))+'px');});
  if(Number.isFinite(restingTop)){const protectedBottom=Math.max(...[...document.querySelectorAll('.hud,#futureIntent')].map(x=>x.getBoundingClientRect().bottom));zone.style.bottom=Math.max(0,frame.bottom-restingTop+8)+'px';zone.style.top=Math.max(98+safeTop,protectedBottom-frame.top+6)+'px';}
  if(gesture?.snapshot()&&gesture.reconcile(api?.capture(gesture.snapshot().card.index))){cleanup();suppressUntil=performance.now()+450;}
 }
 function refresh(index=null){viewport();setupStory();layoutHand(index);}
 const hand=$('#hand'),zone=document.createElement('div');zone.id='cardDropZone';zone.setAttribute('aria-hidden','true');zone.innerHTML='<span>ここで放して使う</span>';$('.game').append(zone);const live=document.createElement('span');live.id='dragStatus';live.className='sr-only';live.setAttribute('role','status');document.body.append(live);
 function cleanup(){ghost?.remove();ghost=null;zone.classList.remove('shown','valid','invalid');hand.classList.remove('drag-active');live.textContent='';}
 function cancelDrag(reason='cancel'){const handled=gesture?.cancel(reason);cleanup();if(handled)suppressUntil=performance.now()+450;return handled;}
 const inside=(x,y)=>{if(document.querySelector('dialog[open]'))return false;const r=zone.getBoundingClientRect();return r.width>0&&r.height>0&&y<restingTop-8&&x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;};
 function bind(callbacks){api=callbacks;gesture=ShinkaFanGesture.createController({select:c=>api.select(c.index),lift:c=>{api.select(c.index);const node=hand.querySelector(`[data-card="${c.index}"]`).closest('.hand-item');ghost=node.cloneNode(true);ghost.removeAttribute('style');ghost.className='drag-ghost';ghost.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));ghost.querySelectorAll('button').forEach(e=>e.tabIndex=-1);ghost.setAttribute('aria-hidden','true');document.body.append(ghost);zone.classList.add('shown');hand.classList.add('drag-active');},move:(x,y,valid)=>{if(ghost){ghost.style.left=x+'px';ghost.style.top=y+'px';}zone.classList.toggle('valid',valid);zone.classList.toggle('invalid',!valid);const message=valid?'放すと使います':'手札へ戻すと取消';if(live.textContent!==message)live.textContent=message;},commit:c=>api.commit(c),cancel:()=>api.dismiss(),finish:handled=>{if(handled)suppressUntil=performance.now()+450;cleanup();}});
 }
 document.addEventListener('pointerdown',ev=>{inputMode='pointer';const a=gesture?.snapshot();if(a&&a.pointerId!==ev.pointerId)cancelDrag('multitouch');},true);
 hand.addEventListener('pointerdown',ev=>{if(!api||document.querySelector('dialog[open]')||ev.isPrimary===false||ev.button>0||ev.target.closest('#playCard,#cancelCard'))return;const item=ev.target.closest('.hand-item'),b=item?.querySelector('[data-card]');if(!b)return;const card=api.capture(Number(b.dataset.card));gesture.begin(ev.pointerId,ev.clientX,ev.clientY,card);});
 window.addEventListener('pointermove',ev=>{const a=gesture?.snapshot();if(!a||a.pointerId!==ev.pointerId)return;const rect=hand.getBoundingClientRect();const mode=gesture.move(ev.pointerId,ev.clientX,ev.clientY,inside(ev.clientX,ev.clientY),api.capture(a.card.index),x=>{if(!centers.length)return null;let best=0;centers.forEach((c,i)=>{if(Math.abs(rect.left+c-x)<Math.abs(rect.left+centers[best]-x))best=i;});return api.capture(best);});if(mode==='drag'||mode==='scrub'){try{if(!hand.hasPointerCapture?.(ev.pointerId))hand.setPointerCapture(ev.pointerId);}catch{}ev.preventDefault();}},{passive:false});
 window.addEventListener('pointerup',ev=>{const a=gesture?.snapshot();if(!a||a.pointerId!==ev.pointerId)return;gesture.end(ev.pointerId,ev.clientX,ev.clientY,inside(ev.clientX,ev.clientY),api.capture(a.card.index));try{hand.releasePointerCapture(ev.pointerId);}catch{};cleanup();});
 window.addEventListener('pointercancel',ev=>{if(gesture?.snapshot()?.pointerId===ev.pointerId)cancelDrag('pointercancel');});hand.addEventListener('lostpointercapture',ev=>{if(gesture?.snapshot()?.pointerId===ev.pointerId)cancelDrag('lostcapture');});
 document.addEventListener('click',ev=>{if(performance.now()<suppressUntil&&ev.target.closest('.hand,.stage,#cardDropZone')){ev.preventDefault();ev.stopImmediatePropagation();}},true);
 document.addEventListener('keydown',ev=>{inputMode='keyboard';if(ev.key==='Escape')cancelDrag('escape');const b=ev.target.closest?.('[data-card]');if(b&&['ArrowLeft','ArrowRight'].includes(ev.key)){ev.preventDefault();cancelDrag('keyboard');const n=Number(b.dataset.card)+(ev.key==='ArrowRight'?1:-1);if(api?.capture(n)){api.select(n);hand.querySelector(`[data-card="${n}"]`)?.focus({preventScroll:true});}}});
 document.addEventListener('click',ev=>{const id=ev.target.closest('button')?.id;if(['helpButton','installApp','deckButton','catalogButton','restart','forgetSave'].includes(id)){cancelDrag('dialog');queueMicrotask(()=>{for(const d of ['catalogDialog','deckDialog'])setupDialog(d);});}});
 hand.addEventListener('focusin',ev=>{const b=ev.target.closest('[data-card]');if(b&&api&&inputMode==='keyboard'&&!restoringFocus&&Number(b.dataset.card)!==selected)api.select(Number(b.dataset.card));});
 window.addEventListener('blur',()=>cancelDrag('blur'));document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelDrag('hidden');});const resized=()=>{cancelDrag('resize');viewport();layoutHand(selected);};window.addEventListener('resize',resized);window.visualViewport?.addEventListener('resize',resized);
 const energy=$('.energy');$('.masthead').prepend(energy);$('.masthead').append($('#endTurn'));const relic=$('#relicStatus');if(relic)$('.hero-hud').append(relic);
 const settings=document.createElement('dialog');settings.id='settingsDialog';settings.setAttribute('aria-labelledby','settingsTitle');settings.innerHTML='<div class="dialog-inner"><h2 id="settingsTitle">旅のメニュー</h2><div class="settings-grid"></div><div class="actions"></div></div>';document.body.append(settings);const menu=settings.querySelector('.settings-grid'),header=$('.header-actions');menu.append(...header.children,$('#deckButton'));const gear=makeButton('⚙',()=>{cancelDrag('menu');api?.dismiss();settings.showModal();settings.querySelector('button:not(:disabled),a')?.focus();});gear.id='settingsButton';gear.setAttribute('aria-label','旅のメニュー');gear.setAttribute('aria-haspopup','dialog');header.append(gear);settings.querySelector('.actions').append(makeButton('戦場へ戻る',()=>settings.close(),'primary'));settings.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))gear.focus({preventScroll:true});});menu.addEventListener('click',ev=>{if(ev.target.closest('button,a'))settings.close();},true);
 for(const id of ['deckDialog','catalogDialog','helpDialog','restartDialog'])$('#'+id)?.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))gear.focus({preventScroll:true});});
 const forecast=$('#futureIntent');if(forecast){forecast.tabIndex=0;forecast.setAttribute('role','button');const explain=()=>{const p=document.createElement('p');p.textContent=forecast.getAttribute('aria-label');showInfo([p],'先の行動（条件付きの基本値）');};forecast.addEventListener('click',explain);forecast.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();explain();}});}
 window.ShinkaLayout=Object.freeze({refresh,refreshHand:layoutHand,setupDialog});window.ShinkaFan=Object.freeze({bind,cancel:cancelDrag,isKeyboard:()=>inputMode==='keyboard',focusBack(element){if(!element)return;restoringFocus=true;try{element.focus({preventScroll:true});}finally{restoringFocus=false;}}});viewport();
})();
