const STATUS_LABEL={waiting:'待機',queued:'生成待ち',generating:'生成中',qa:'品質確認中',needs_fix:'要修正',regenerate:'再生成',complete:'完成',adopted:'採用',github_synced:'GitHub反映済み'};
const TYPE_LABEL={card:'カード',enemy:'敵',class:'クラス',character:'主人公',part:'パーツ',background:'背景'};
const STORAGE_KEY='shinka-asset-factory-v1';
let baseQueue=null,data=null,selectedId=null,filter='all';
const $=s=>document.querySelector(s);
async function load(){const res=await fetch('./asset-factory/queue.json',{cache:'no-store'});baseQueue=await res.json();const saved=localStorage.getItem(STORAGE_KEY);data=saved?mergeSaved(baseQueue,JSON.parse(saved)):structuredClone(baseQueue);selectedId=data.jobs.find(j=>!['adopted','github_synced'].includes(j.status))?.asset_id||data.jobs[0]?.asset_id||null;bindTop();render()}
function mergeSaved(base,saved){const byId=new Map((saved.jobs||[]).map(j=>[j.asset_id,j]));const merged=structuredClone(base);merged.jobs=merged.jobs.map(j=>({...j,...(byId.get(j.asset_id)||{})}));return merged}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function current(){return data.jobs.find(j=>j.asset_id===selectedId)}
function isDone(j){return ['complete','adopted','github_synced'].includes(j.status)}
function pct(type){const list=data.jobs.filter(j=>j.type===type);return list.length?Math.round(list.filter(isDone).length/list.length*100):0}
function bindTop(){$('#nextBtn').onclick=()=>{const job=data.jobs.find(j=>['waiting','queued','needs_fix','regenerate'].includes(j.status));if(!job)return alert('待機中のジョブはありません。');selectedId=job.asset_id;job.status='generating';job.attempts=(job.attempts||0)+1;save();render()};$('#resetBtn').onclick=()=>{if(!confirm('ローカルの進捗を初期状態へ戻しますか？'))return;localStorage.removeItem(STORAGE_KEY);data=structuredClone(baseQueue);selectedId=data.jobs[0]?.asset_id||null;render()};$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='asset-factory-queue.json';a.click();URL.revokeObjectURL(a.href)}}
function render(){renderSummary();renderFilters();renderQueue();renderDetail()}
function renderSummary(){const cards=[['card','カード'],['enemy','敵'],['class','クラス']];const total=data.jobs.length,done=data.jobs.filter(isDone).length;$('#summary').innerHTML=[...cards.map(([type,label])=>summaryCard(label,data.jobs.filter(j=>j.type===type).length,data.jobs.filter(j=>j.type===type&&isDone(j)).length,pct(type))),summaryCard('全体',total,done,total?Math.round(done/total*100):0)].join('')}
function summaryCard(label,total,done,percent){return `<article class="summary-card"><p class="summary-label">${label}</p><strong>${done} / ${total}</strong><div class="bar"><span style="width:${percent}%"></span></div><p class="summary-meta">${percent}% 完了</p></article>`}
function renderFilters(){const types=['all',...new Set(data.jobs.map(j=>j.type))];$('#filters').innerHTML=types.map(t=>`<button class="filter ${filter===t?'active':''}" data-filter="${t}">${t==='all'?'すべて':TYPE_LABEL[t]||t}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderQueue();renderFilters()})}
function renderQueue(){const list=data.jobs.filter(j=>filter==='all'||j.type===filter);$('#queueCount').textContent=`${list.length} jobs`;$('#queueList').innerHTML=list.map((j,i)=>`<article class="job ${j.asset_id===selectedId?'selected':''}" data-id="${j.asset_id}"><div class="job-index">${String(i+1).padStart(2,'0')}</div><div><h3>${escapeHtml(j.name)}</h3><p>${TYPE_LABEL[j.type]||j.type} · ${j.transparent?'透過PNG':'背景ありPNG'} · ${j.aspect_ratio}</p></div><span class="status status-${j.status}">${STATUS_LABEL[j.status]||j.status}</span></article>`).join('');document.querySelectorAll('.job').forEach(el=>el.onclick=()=>{selectedId=el.dataset.id;renderQueue();renderDetail()})}
function renderDetail(){const j=current();if(!j){$('#detailPanel').innerHTML='<div class="empty-state"><h2>ジョブなし</h2></div>';return}const qa=qaRules(j);$('#detailPanel').innerHTML=`<div class="detail-head"><div><p class="eyebrow">${TYPE_LABEL[j.type]||j.type}</p><h2>${escapeHtml(j.name)}</h2><p class="sub">${escapeHtml(j.asset_id)}</p></div><div class="detail-actions"><button data-act="generating">生成開始</button><button data-act="qa">QAへ</button><button data-act="needs_fix">要修正</button><button data-act="complete">完成</button><button data-act="adopted">採用</button></div></div><div class="meta-grid"><div class="meta"><label>状態</label><b>${STATUS_LABEL[j.status]||j.status}</b></div><div class="meta"><label>生成回数</label><b>${j.attempts||0}</b></div><div class="meta"><label>形式</label><b>${j.format?.toUpperCase()||'PNG'}</b></div><div class="meta"><label>背景</label><b>${j.transparent?'完全透過':'背景あり'}</b></div></div><div class="field"><label>生成プロンプト</label><textarea id="promptField">${escapeHtml(j.prompt||'')}</textarea></div><div class="field"><label>ネガティブ条件</label><textarea id="negativeField">${escapeHtml((j.negative||[]).join(' / '))}</textarea></div><div class="field"><label>GitHub保存先</label><input id="pathField" value="${escapeAttr(j.save_path||'')}" /></div><p class="path">現在: ${escapeHtml(j.current_path||'未登録')}</p><div class="qa-box"><div class="qa-title"><b>品質チェック</b><span>${Object.values(j.qa||{}).filter(Boolean).length} / ${qa.length}</span></div><div class="qa-list">${qa.map((q,idx)=>`<label class="qa-item"><input type="checkbox" data-qa="q${idx}" ${(j.qa||{})['q'+idx]?'checked':''}><span>${escapeHtml(q)}</span></label>`).join('')}</div></div><div class="image-preview">${j.current_path?`<img src="./${escapeAttr(j.current_path)}" alt="${escapeAttr(j.name)}">`:`<div class="image-placeholder"><b>画像未登録</b><p>生成画像の保存先をキューへ紐づけるとここに表示されます。</p></div>`}</div><div class="notice">Asset Factory v0.1では、生成とGitHub書き込みは外部ワーカー接続前のため状態管理まで。APIキーをブラウザに置かない設計です。</div>`;document.querySelectorAll('[data-act]').forEach(btn=>btn.onclick=()=>setStatus(btn.dataset.act));$('#promptField').onchange=e=>{j.prompt=e.target.value;save()};$('#negativeField').onchange=e=>{j.negative=e.target.value.split('/').map(s=>s.trim()).filter(Boolean);save()};$('#pathField').onchange=e=>{j.save_path=e.target.value;save()};document.querySelectorAll('[data-qa]').forEach(cb=>cb.onchange=()=>{j.qa=j.qa||{};j.qa[cb.dataset.qa]=cb.checked;save();renderDetail()})}
function setStatus(status){const j=current();if(!j)return;if(status==='generating')j.attempts=(j.attempts||0)+1;j.status=status;save();render()}
function qaRules(j){const common=['1素材だけで構成されている','文字・数字・UIが混ざっていない','指定の世界観・画風に合っている','主要要素が画像内で切れていない'];if(j.type==='card')return [...common,'カード枠が描かれていない','縦長カードにトリミングしやすい','魔法の種類が小表示でも判別できる'];if(j.type==='enemy')return [...common,'敵が1体のみ','全身が収まっている','背景が完全透過','武器・マントが切れていない'];if(j.type==='class'||j.type==='character')return [...common,'同一主人公として見える','全身が収まっている','背景が完全透過','杖・髪・衣装が切れていない'];return common}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function escapeAttr(s=''){return escapeHtml(s)}
load().catch(err=>{$('#detailPanel').innerHTML=`<div class="empty-state"><h2>読み込みエラー</h2><p>${escapeHtml(err.message)}</p></div>`});